name: simuk-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python >= 3.13
  - pip
  - pymc>=5.20.1
  - bambi>=0.13.0
  - arviz>=0.20.0
  - pytest-cov>=2.6.1
  - pytest>=4.4.0
  - pre-commit>=2.19
  - ruff==0.15.13
